version: '3.8'

services:
  backend:
    container_name: enrollment-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

  frontend:
    container_name: enrollment-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

networks:
  imraffy-network:
    external: true
